### ISSUE TITLE
Doesn't Scale

### ISSUE THREAD

**Issue by aadil058** [AminaG/passport-one-session-per-user#1]
Do you know how much time it's gonna take for a productive app, let's say total logged in users are around 10000. First of all it fetches all 10000 users and then it over them one by one to check if session id is already exist or not, You can do much better than this :), but a good idea 👍

**Comment by Aminadav** [comment]
Look on it as a prototype. You can use the Strategy, and implement another algorithm.
This is the beauty of open-source.
